name: build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - develop

jobs:
  Windows_2022_32bit:
    runs-on: windows-2022
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Configure CMake
        shell: cmd
        run: |
          mkdir build
          cmake -DCMAKE_BUILD_TYPE=Release -S . -B build -A Win32
      - name: Build
        shell: cmd
        run: |
          # https://stackoverflow.com/a/19026241
          cmake --build build --config Release
